# Generated by Django 3.1.7 on 2021-04-04 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeBase',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('shapebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shapes.shapebase')),
                ('length', models.IntegerField()),
                ('diagonal_one', models.IntegerField()),
                ('diagonal_two', models.IntegerField()),
            ],
            bases=('shapes.shapebase',),
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('shapebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shapes.shapebase')),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
            bases=('shapes.shapebase',),
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('shapebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shapes.shapebase')),
                ('side', models.IntegerField()),
            ],
            bases=('shapes.shapebase',),
        ),
        migrations.CreateModel(
            name='Triangle',
            fields=[
                ('shapebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shapes.shapebase')),
                ('base', models.IntegerField()),
                ('adjacent', models.IntegerField()),
                ('opposite', models.IntegerField()),
            ],
            bases=('shapes.shapebase',),
        ),
    ]
