# Generated by Django 3.1.7 on 2021-04-05 03:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamond',
            name='shapebase_ptr',
        ),
        migrations.RemoveField(
            model_name='rectangle',
            name='shapebase_ptr',
        ),
        migrations.RemoveField(
            model_name='square',
            name='shapebase_ptr',
        ),
        migrations.RemoveField(
            model_name='triangle',
            name='shapebase_ptr',
        ),
        migrations.AddField(
            model_name='diamond',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diamond',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diamond',
            name='name',
            field=models.CharField(default='shape', max_length=200),
        ),
        migrations.AddField(
            model_name='diamond',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rectangle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rectangle',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rectangle',
            name='name',
            field=models.CharField(default='shape', max_length=200),
        ),
        migrations.AddField(
            model_name='rectangle',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='square',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='square',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='square',
            name='name',
            field=models.CharField(default='shape', max_length=200),
        ),
        migrations.AddField(
            model_name='square',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='triangle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triangle',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='triangle',
            name='name',
            field=models.CharField(default='shape', max_length=200),
        ),
        migrations.AddField(
            model_name='triangle',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ShapeBase',
        ),
    ]
